
#  Quiz Leaderboard
quiz.regNo=RA2311008020034

# API Configuration 
quiz.api.base-url=https://devapigw.vidalhealthtpa.com/srm-quiz-task
quiz.api.poll-count=10
quiz.api.poll-delay-ms=5000

#Server 
server.port=8080
spring.main.web-application-type=none
